# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  serializer:
    serialize_null: true
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      xml:  true
      json: true
    templating_formats:
      html: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  body_listener: true
  body_converter:
    enabled: true
    validate: true
    #array_normalizer: fos_rest.normalizer.camel_keys
  disable_csrf_role: ROLE_API
  routing_loader:
    default_format: json